### ISSUE TITLE
Duplicate names shown in search results

### ISSUE THREAD

**Issue by dorranh** [tweag/nixpkgs-graph-explorer#105]
When searching for a package by name, duplicate names appear in the search results. This makes the UI harder to use since fewer unique items are visible on a given page and makes for a confusing UX. Ideally the UI would only show unique package names.

![image](https://github.com/tweag/nixpkgs-graph-explorer/assets/52341904/1eb33b72-b2c2-4348-8eae-b6c99c9e252d)

**Comment by GuillaumeDesforges** [comment]
Thinking about it, the "search" par might be better to search not `pname` but `attributePath`

https://github.com/tweag/nixpkgs-graph-explorer/blob/2d6aacd0199e57bb5e871ffbf873f9fa4b319e2d/core/explorer/extract/nixpkgs-graph.nix#L32

This would also yield results like search.nixos.org, which people seem to expect.

**Comment by GuillaumeDesforges** [comment]
IMO, getting an incomplete list (with possibly the wrong, unexpected derivations) of results does not fix the UX. It would most probably break even more the tool.

**Comment by dorranh** [comment]
@GuillaumeDesforges, Just to clarify: I believe the current behavior in these cases would be that the graph would include the subgraphs for all derivations with the same `pname` rather than to only show one or the other (though we should double-check that this is indeed the case). If so, would you still say that this approach is not an improvement over the current behavior?

**Comment by GuillaumeDesforges** [comment]
Closed by #116
