### ISSUE TITLE
Fix nightly pipeline

### ISSUE THREAD

**Issue by smelc** [tweag/nixpkgs-graph-explorer#109]
Since its introduction in https://github.com/tweag/nixpkgs-graph-explorer/pull/102, the nightly pipeline does not work, as visible in the [list of runs of actions](https://github.com/tweag/nixpkgs-graph-explorer/actions) (look for _Nightly_ entries).

This issue keeps track of making it work. At the moment the output from the failing step doesn't give a hint:

```shell
# We write the output to a file, not to standard output,
  # We write the output to a file, not to standard output,
  # to keep log size small.
  nix develop --command bash -c 'cd core && poetry run python -m explorer.extract graph.json'
  wc -l graph.json
  shell: /usr/bin/bash -e {0}
trace: warning: qt5 now uses makeScopeWithSplicing which does not have "overrideScope'", use "overrideScope".
Error: Process completed with exit code 14[3](https://github.com/tweag/nixpkgs-graph-explorer/actions/runs/5041666607/jobs/9041557263#step:5:3).
```

**Comment by GuillaumeDesforges** [comment]
Thanks @smelc. Possibly, GitHub thinks we're mining bitcoin 😄 

We might try to run the pipeline on a minimal flake instead of the whole `github:nixos/nixpkgs/master` flake.

**Comment by smelc** [comment]
> We might try to run the pipeline on a minimal flake instead of the whole github:nixos/nixpkgs/master

@GuillaumeDesforges> yep indeed, the pipeline fails as follows:

![image](https://github.com/tweag/nixpkgs-graph-explorer/assets/634720/170c86c9-7c0a-4652-9ed9-d2ce1bd55a26)

which likely indicates that it simply runs out of memory (the GitHub runners being pretty cheap machines, that's not a surprise)

**Comment by GuillaumeDesforges** [comment]
https://github.com/tweag/nixpkgs-graph-explorer/pull/108 could help fix this issue as it consumes way less memory.
