### ISSUE TITLE
As a user, I am able to select from a number of sample queries to run.

### ISSUE THREAD

**Issue by jeicher** [tweag/nixpkgs-graph-explorer#22]
**Is your feature request related to a problem? Please describe.**
Users often report being unable to intuitively understand the types of queries they could submit to the platform. This is partially due to a lack of familiarity with the Gremlin query language.

**Describe the solution you'd like**
A simple solution would be to provide a few example queries in the UI. These could be a mix of queries that the user could run as is, and template queries that require user input. As an MVP, all that this feature would need to do is to populate the query input with Gremlin code.

**Describe alternatives you've considered**
No alternatives were considered.

**Additional context**
As an example, this site (which analyses PostgreSQL queries) offers something similar to this feature.
![image](https://user-images.githubusercontent.com/5111796/213190489-54d12249-48ca-4375-a741-d1832b19b8e8.png)

**Comment by zz1874** [comment]
Apart from some example queries mentioned in #23 , another example can be:

- find the **subgraph** between packages A and B: every connections from A to B

**Comment by GuillaumeDesforges** [comment]
Users don't really want or need to query themselves.
