### ISSUE TITLE
Add several properties to the existing database

### ISSUE THREAD

**Issue by zz1874** [tweag/nixpkgs-graph-explorer#23]
**Is your feature request related to a problem? Please describe.**
For now, the project is focused on querying package dependencies, but the use cases are a bit limited and users may want to explore more properties than `buildInputs`, `outputPath`, `path`, `pname`, and `version`.

**Describe the solution you'd like**
Here is a list of properties users might be interested in and their corresponding example queries:

- propagatedBuildInputs
    -  (also mentioned in #19 )
- package broken state
     - package **broken state** is a boolean 1..1 property of a package  
     - example query:  
         - how many broken packages are there?
         - which broken packages depend on package X?
- maintainer
    - package maintainer is a list of names: either a list of properties, or edges to maintainer nodes
    - `maintainer` is a 0..n property of a package  
    - example query:
        - which packages does "infinisil" maintain?
- license
    - license is a 0..n property of each package  
    - example query:   
        - generate the set of licences that a certain package and its transitive dependency closure has

 We can add these properties as columns in the database. So long as they're added, we can show some example queries using the solution of #22 .

**Describe alternatives you've considered**
There aren't any alternatives that were considered.

**Additional context**
There aren't any additional contexts.

**Comment by GuillaumeDesforges** [comment]
@zz1874 which information from this list is not available in the graph database?

**Comment by zz1874** [comment]
Right now we only include the parsed `pname` and `outputPath` in the graph database. 
We have `brokenState` and `license` in the extracted data not ingesting to the graph database yet. We don't have `closure size`(not available in nixpkgs) and `maintainers` in the extracted data.

**Comment by smelc** [comment]
> closure size

For our prospect project with [PDT Partners](https://pdtpartners.com/) (led by @ConnorBaker), we are interested in reducing closure size of CUDA-related packages. @ConnorBaker> could you have a look if you can use https://nixpkgs-graph.app/ to see the packages that matter to PDT? If not, what is blocking you? If yes, do  you confirm you would be interested in viewing the closure size in the UI?

**Comment by GuillaumeDesforges** [comment]
Let's make this issue about data we can extract from the pure evaluation, and data from additional sources in  #98

**Comment by GuillaumeDesforges** [comment]
Adding that to the roadmap, should be fairly straightforward to add

**Comment by GuillaumeDesforges** [comment]
We will need the licenses for genealogos
