### ISSUE TITLE
As a user, I am able to reset the graph when zooming out too much

### ISSUE THREAD

**Issue by zz1874** [tweag/nixpkgs-graph-explorer#24]
**Is your feature request related to a problem? Please describe.**
If a user zooms out the graph too much, the nodes/edges cannot be found anymore.

**Describe the solution you'd like**
Add a button to reset the graph.

**Describe alternatives you've considered**
There aren't any alternatives that were considered.

**Additional context**
There aren't any additional contexts.

**Comment by GuillaumeDesforges** [comment]
More than resetting the zoom, we could use more tooling on the zoom:

- button to zoom in
- button to zoom out
- current zoom displayed (e.g. in %)
- input to set the zoom (e.g. in %)
- button to reset zoom to default value
- button to reset zoom to default value AND reset position to default position

**Comment by GuillaumeDesforges** [comment]
Wheel sensitivity has been reduced a lot so zooming is smoother, the original issue does not really appear anymore.
