### ISSUE TITLE
Test Nix extraction

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/nixpkgs-graph-explorer#34]
Currently, the Nix extraction process and mostly `nixpkgs-graph.nix` are not tested.

This issue gathers suggestions and tracks improvements.

**Comment by GuillaumeDesforges** [comment]
Not in project as this needs to be turned into actionables.

First idea is to use the `core` model introduced by #56 to check the shape of the output

**Comment by GuillaumeDesforges** [comment]
A model and schema was created, it is not ideal but enough for now.

**Comment by smelc** [comment]
Would introducing a nightly pipeline that runs extraction help here? You would catch _hey we need to update something_ errors, right?
