### ISSUE TITLE
Centralize logic for graph I/O

### ISSUE THREAD

**Issue by dorranh** [tweag/nixpkgs-graph-explorer#41]
As a part of the changes in #39, a new module called `explorer.graph` was added which defines our core data model and key operations for interacting with the graph. As a matter of organization, it would be nice to have the `etl` process utilize this module to ensure that we are working with the same data model, etc. This will require us to add some additional data types to `graph` for elements such as edges and port functions for writing edges to the graph over to this module.

**Comment by GuillaumeDesforges** [comment]
Requires
- [ ] #41
- [ ] #65
