### ISSUE TITLE
Add additional context information to UI

### ISSUE THREAD

**Issue by dorranh** [tweag/nixpkgs-graph-explorer#43]
Even with the refreshed UI in #37, the UI currently lacks a lot of context for helping users understand the project and application. It would be helpful to add additional information such as:

- References to Tweag and Modus Create
- A link to the GitHub repo
- An indication of which nixpkgs revision is being rendered
- Help text explaining how to use the application
- References to Gremlin language docs

**Comment by GuillaumeDesforges** [comment]
Closed in #54 and #58
