### ISSUE TITLE
Add CI check for backend / python code

### ISSUE THREAD

**Issue by jlesquembre** [tweag/nixpkgs-graph-explorer#62]
We should add some basic checks on CI for the python code (code formatting, linting, ....).
See https://github.com/tweag/nixpkgs-graph-explorer/pull/61#pullrequestreview-1374734751 and https://github.com/tweag/nixpkgs-graph-explorer/pull/61#issuecomment-1499079108 for ideas.

**Comment by GuillaumeDesforges** [comment]
- [ ] formatting
- [ ] linting
