### ISSUE TITLE
The name of outputPath has values other than OUT, DEV, and LIB

### ISSUE THREAD

**Issue by zz1874** [tweag/nixpkgs-graph-explorer#67]
In the JSON schema we created, we only include three kinds of `outputPathName`:
```
    OUT = "out"
    LIB = "lib"
    DEV = "dev"
```
However, there are 259 `outputPathName`s in the data we extracted from nix (got from the function `get_output_names` in `etl/etl.py`). It will not work out when we try to add a package with `outputPathAll = {"doc":"/nix/store/a"}`. 
Should we ignore the `outputPath` with unrecognized `outputPathName` or we create another name called `OTHERS` or so?
Any ideas? @GuillaumeDesforges @dorranh

**Comment by GuillaumeDesforges** [comment]
Nicely spotted.

I'd go for a plain str for the outputPath name since there are so many options.

**Comment by zz1874** [comment]
fixed by #75
