### ISSUE TITLE
Package table fails to load next page when no search term is specified

### ISSUE THREAD

**Issue by dorranh** [tweag/nixpkgs-graph-explorer#87]
**Describe the bug**
Attempting to navigate through pages in the package table fails when no search term is specified.

![image](https://github.com/tweag/nixpkgs-graph-explorer/assets/52341904/d522d1fd-a7d3-4a97-96bd-893eabce156c)

**To Reproduce**
Navigate to the web page and click on the "next" arrow as shown below.

![image](https://github.com/tweag/nixpkgs-graph-explorer/assets/52341904/bef1d45f-be61-4a67-9c98-afb358454e99)

**Expected behavior**
The next page should load.

**Environment**
 - OS name + version: Chrome
 - Version of the code: 22993a991ade49e1c93d6c177008756294da5ca6

**Comment by GuillaumeDesforges** [comment]
I would favor not making a search when the bar is empty, there is no point in "browsing" all derivations
