### ISSUE TITLE
Display query error

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/nixpkgs-graph-explorer#91]
**Is your feature request related to a problem? Please describe.**
When a request is done using an invalid query, I want to see the error to fix the query.
For now, it only displays "Error fetching graph data :( Please check your query and try again later".

<img width="704" alt="image" src="https://github.com/tweag/nixpkgs-graph-explorer/assets/1882000/f1a8df02-9feb-49a0-a721-cef717e1df74">

**Describe the solution you'd like**
When the query is invalid, I want to see the query error.

**Comment by GuillaumeDesforges** [comment]
@florentc I think this was resolved by #112 ?

**Comment by florentc** [comment]
No it was not. Not yet.

**Comment by GuillaumeDesforges** [comment]
Querying has been removed.
